#!/bin/bash
default_folder_path="/home/lorev/current_course/"
if [[ $1 == /home/lorev/current_course/* ]]; then
    folder_path="$1"
else
    folder_path="${default_folder_path}$1"
fi
echo "$folder_path"

mapfile -t files < <(find "$folder_path" -mindepth 1 -maxdepth 1 -type f \( ! -iname "*.aux" -a ! -iname "*.log" -a ! -iname "*.latexmain" -a ! -iname "*.out" -a ! -iname "*.toc" -a ! -regex '.*/lec_[0-9][0-9]\.tex' -a ! -iname "*.fdb_latexmk" -a ! -iname "*.fls"  -a ! -iname "*.gz" -a ! -iname "*.nav" -a ! -iname "*.sty" -a ! -iname "*.snm" \) | sort)


if [[  ${#files[@]} -eq 0 ]]; then
    echo "Nessun file trovato nel percorso specificato."
    exit 1
fi

file_names=""
for file in "${files[@]}"; do
    file_name=$(basename "$file")
    file_names+="$file_name"
 # Add a newline if not the last file
    if [[ $i -lt $(( ${#files[@]} - 1 )) ]]; then
        file_names+=$'\n'
	echo "$i"
    fi
done
# Debug: stampa i nomi dei file
echo "Nomi dei file trovati:"
echo "$file_names"

selected_file_name=$(echo -e "$file_names" | rofi -dmenu -kb-custom-1 "Ctrl+y" -p "Scegli un file" -i -auto-select)
# Debug: controlla se Rofi ha ricevuto input
if [[ -z "$selected_file_name" ]]; then
    echo "Nessun file selezionato."
    exit 1
fi

# Trova il percorso completo del file selezionato
selected_file=""
for file in "${files[@]}"; do
    if [[ "$(basename "$file")" == "$selected_file_name" ]]; then
        selected_file="$file"
        break
    fi
done

# Debug: controlla se il file selezionato è stato trovato
if [[ -z "$selected_file" ]]; then
    echo "File selezionato non trovato."
    echo "File selezionato: '$selected_file'"
    exit 1
fi
# Funzione per gestire la rinominazione del file
function rename_file {
    local file="$1"
    echo "sto rinominando il file"
    if [[ "$file" == *.mp4 ]]; then
        if [[ "$file" == done-* ]]; then
            new_name="${file#done-}"
            mv "$file" "$new_name"
            echo "File rinominato in: $new_name"
        else
            new_name="done-$(basename "$file")"
            mv "$file" "$(dirname "$file")/$new_name"
            echo "File rinominato in: $new_name"
        fi
    else
        echo "Rinominazione non applicabile: non è un file mp4."
    fi
}
# Trap per custom keybinding
if [[ "$selected_file_name" == "Ctrl+y" ]]; then
    rename_file "$selected_file"
    exit 0
fi
 
# Esegui l'applicazione appropriata
case "$selected_file" in
    *.pdf)
        zathura "$selected_file"
        ;;
    *.mp4)
	vlc "$selected_file"
	;;
    *)
        alacritty nvim "$selected_file"
        ;;
esac
